# Generated by Django 5.1 on 2024-09-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_exam_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date_uploaded', models.DateField()),
                ('pdf_file', models.FileField(upload_to='study_materials/')),
            ],
        ),
    ]
