# Generated by Django 5.1 on 2024-09-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_studymaterial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studymaterial',
            table='teacher_studymaterial',
        ),
    ]
