# Generated by Django 5.1 on 2024-09-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_user',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
