# Generated by Django 5.1 on 2024-10-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_exam_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
