# Generated by Django 5.1 on 2024-10-01 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_examname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
