# Generated by Django 5.1 on 2024-10-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_exam_name_exam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='exam',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
