# Generated by Django 5.1 on 2024-10-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_subject_exam_delete_exam_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='registered', max_length=10)),
            ],
        ),
    ]
