# Generated by Django 5.1 on 2024-10-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
