# Generated by Django 5.1 on 2024-10-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_exam_student_hallticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallticket',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='hallticket',
            name='student',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='HallTicket',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
