# Generated by Django 5.1 on 2024-09-03 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_userprofile_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='UserProfile',
        ),
    ]
