# Generated by Django 5.1 on 2024-09-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_teacher_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_user',
            name='user',
        ),
    ]
