# Generated by Django 5.1 on 2024-09-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_teacher_user_password_alter_teacher_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_user',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher_user',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
        migrations.AlterField(
            model_name='teacher_user',
            name='photo',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='photos/'),
        ),
    ]
